name: basic_mathematical_operations
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/Confetti-original.json
